apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  labels:
    env: production
    tier: cicd
    app: jenkins
    name: jenkins-ingress
spec:
  rules:
    - host: <젠킨스 도메인> # TODO
      http:
        paths:
          - path: /
            backend:
              serviceName: jenkins
              servicePort: 8080