apiVersion: v1
kind: Service
metadata:
  name: portal-service
  labels:
    env: production
    tier: backend
    app: portal-service
    name: portal-service-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    env: production
    tier: backend
    app: portal-service
    name: portal-service-pod