apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
  labels:
    env: production
    tier: logging
    app: kibana
    name: kibana-ingress
spec:
  rules:
    - host: <ELK Kibana 도메인> # TODO
      http:
        paths:
          - path: /
            backend:
              serviceName: kibana
              servicePort: 5601