spring:
  r2dbc:
    url: r2dbc:mysql://${mysql.hostname:localhost}:3306/reservation?serverTimezone=Asia/Seoul&autoReconnect=true&validationQuery=select%201&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&connectionCollation=utf8mb4_unicode_ci
    username: msaportal
    password: msaportal
  cloud:
    bus:
      destination: springCloudBus
    stream:
      function:
        definition: inventoryUpdated;busConsumer # 예약 요청후 물품 재고업데이트 결과에 이벤트에 대한 consumer function & springcloudbus consumer function
      bindings:
        busConsumer-in-0:
          destination: ${spring.cloud.bus.destination}
        reserveRequest-out-0: # 예약 요청후 물품 재고업데이트 이벤트에 대한 supplier binding
          destination: reserve-request.topic # queue name
          group: reserved
        inventoryUpdated-in-0: # 예약 요청후 물품 재고업데이트 결과에 이벤트에 대한 consumer binding
          destination: inventory-updated.topic # queue name
          group: reserved
