apiVersion: v1
kind: Service
metadata:
  name: board-service
  labels:
    env: production
    tier: backend
    app: board-service
    name: board-service-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    env: production
    tier: backend
    app: board-service
    name: board-service-pod