apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reserve-check-service-hpa-cpu
  labels:
    env: production
    tier: backend
    app: reserve-check-service
    name: reserve-check-service-hpa-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reserve-check-service-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70