apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-admin-hpa-cpu
  labels:
    env: production
    tier: frontend
    app: admin
    name: frontend-admin-hpa-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-admin-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70